# if you call srand, you have to "undo" the effects by calling it again with no arguments.
# this will effectively call srand with a random number generated by the system. 
# to see the effects of this, run this program twice, and notice that the first
# four outputs are always the same, while the last 4 outputs are different because they 
# received a different seed

srand(1986)

puts rand(100)
puts rand(100)
puts rand(100)
puts rand(100)

srand()

puts rand(100)
puts rand(100)
puts rand(100)
puts rand(100)
